### ISSUE TITLE
Why is my zsh already in version 5.8 while it said that it's requiered to be greater than version 5.8?

### ISSUE THREAD

**Issue by olivertzeng** [romkatv/zsh-bench#21]
❯ ~/zsh-bench/zsh-bench
zsh-bench: zsh >= 5.8 is required to execute this script
❯ echo $ZSH_VERSION
5.8

**Comment by olivertzeng** [comment]
> Because.

Sorry for my impoliteness bro. @romkatv

**Comment by olivertzeng** [comment]
and that was fast thanks!

**Comment by olivertzeng** [comment]
❯ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
oh there you go

**Comment by olivertzeng** [comment]
can you please open this issue again? I've used your zsh-bin installer btw

**Comment by romkatv** [comment]
You need to change `PATH` so that zsh 5.8 is the first to be found.

**Comment by olivertzeng** [comment]
How do i do it? (PATH is really a pain in my ass)

**Comment by romkatv** [comment]
Maybe this? https://stackoverflow.com/questions/7703041/editing-path-variable-on-mac/16288733#16288733

If this doesn't work, google it.

**Comment by olivertzeng** [comment]
ok

**Comment by olivertzeng** [comment]
(although the time is now 19)

**Comment by romkatv** [comment]
> where was the zsh-bin installed?

That's a question for you.

I'm going to close the issue again.

**Comment by olivertzeng** [comment]
so should i actually open an issue in the zsh-bin repo?

**Comment by olivertzeng** [comment]
-d DIR

    Install to this directory. If specified more than once, present
    an interactive dialog to choose the directory. Empty argument
    means a custom directory (requires manual user input). If '-d'
    is not specified, the effect is idential to this:

      -d /usr/local -d ~/.local -d ""


so its installed in /usr/local & ~/.local

**Comment by romkatv** [comment]
> so should i actually open an issue in the zsh-bin repo?

No, of course not. Neither of my repos is appropriate to ask for help with administering your computer.

**Comment by olivertzeng** [comment]
> > so should i actually open an issue in the zsh-bin repo?
> 
> No, of course not. Neither of my repos is appropriate to ask for help with administering your computer.

oops sorry

**Comment by olivertzeng** [comment]
thanks @romkatv I fixed it because you implied to me that ill have to do my own work.
I simply change from 
`PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
  export PATH"`
to
`PATH=/bin:/usr/bin:/usr/local/bin:${PATH}
  export PATH="/usr/local/bin:$PATH"`
and it worked
`❯ zsh --version
zsh 5.8 (x86_64-apple-darwin17.7.0)`

**Comment by olivertzeng** [comment]
and it's my first time trying to solve problems for myself btw

**Comment by romkatv** [comment]
Well done.
