### ISSUE TITLE
zsh-bench runs indefinitely long

### ISSUE THREAD

**Issue by Magniquick** [romkatv/zsh-bench#27]
<img width="772" alt="Screenshot 2024-02-10 at 5 22 41 PM" src="https://github.com/romkatv/zsh-bench/assets/67406856/435320be-b61f-4515-b141-d14dadb2fc2b">

My .zshrc is incredibly nonstandard, so I'll try to trim it down and see what causes the issue.
on that note, how much time should it take for it to finish running / output something else ?

**Comment by romkatv** [comment]
> how much time should it take for it to finish running / output something else ?

On my machine `~/zsh-bench/zsh-bench --iters 1` takes 13s.

**Comment by romkatv** [comment]
By the way, if your username contains sensitive information, consider changing it. Then you won't have to censor it.

**Comment by Magniquick** [comment]
> By the way, if your username contains sensitive information, consider changing it. Then you won't have to censor it.

too lazy right now : )
Thanks for the advise - maybe later

**Comment by Magniquick** [comment]
seems like these lines cause the issue:
```zsh
if $ZDOTDIR/plugins/iterm2/utilities/it2check; then
  is_iterm=True
fi
```
(I use that var to enable iterm2 specific things)
it's crucial to note that it is that script that causes issues - merely setting the variable causes no issues
here is the file in question:
[it2check.txt](https://github.com/romkatv/zsh-bench/files/14229240/it2check.txt)

**Comment by romkatv** [comment]
I can see how that script can break things. It doesn't just break zsh-bench, it breaks your shell, too. If you start zsh and start typing, that script may read stuff from the TTY it wasn't supposed to. To add insult to injury, this script is very slow.

Consider removing that check and simply doing stuff unconditionally.

**Comment by Magniquick** [comment]
> I can see how that script can break things. It doesn't just break zsh-bench, it breaks your shell, too. If you start zsh and start typing, that script may read stuff from the TTY it wasn't supposed to. To add insult to injury, this script is very slow.
> 
> Consider removing that check and simply doing stuff unconditionally.

ouch, thanks.
Should I file a bug ? would this even be considered as one - as this 'breaking stuff' seems to be part of its function ?

(BTW, thanks for your work in the zsh field - I am currently using [one of your diy configs](ttps://github.com/romkatv/zsh-bench/blob/master/configs/diy%2B%2Bfsyh/skel/.zshrc) and it works extremely well for me !)

**Comment by romkatv** [comment]
Sure, You can file a bug, but I'm not sure how useful that will be. Basically, apart from being slow, this script has these issues:

1. It consumes pending input. If you start typing while this script is running (while for you means typing while zsh is initializing), a portion of that input may silently disappear.
2. It assumes that no input comes between dropping all buffered input and reading the response to the DSR. It's a race condition.

In general, reading TTY input and dropping it on the floor is a bad idea.

It is possible to implement this script correctly and make it fast, at least in zsh, but it's non-trivial.

**Comment by romkatv** [comment]
> I am currently using [one of your diy configs](https://github.com/romkatv/zsh-bench/blob/master/configs/diy%2B%2Bfsyh/skel/.zshrc) as a base

Just to clarify: the existence of this config in my repo does not mean that I endorse it. If you like it, by all means.

**Comment by Magniquick** [comment]
> Sure, You can file a bug, but I'm not sure how useful that will be. Basically, apart from being slow, this script has these issues:
> 
>     1. It consumes pending input. If you start typing while this script is running (while for you means typing while zsh is initializing), a portion of that input may silently disappear.
> 
>     2. It assumes that no input comes between dropping all buffered input and reading the response to the DSR. It's a race condition.
> 
> 
> In general, reading TTY input and dropping it on the floor is a bad idea.
> 
> It is possible to implement this script correctly and make it fast, at least in zsh, but it's non-trivial.

guess I'll more back to reading the env variables.



> > I am currently using [one of your diy configs](https://github.com/romkatv/zsh-bench/blob/master/configs/diy%2B%2Bfsyh/skel/.zshrc) as a base
> 
> Just to clarify: the existence of this config in my repo does not mean that I endorse it. If you like it, by all means.

ofc - but it does work well for my workflow - and I dont see any large drawbacks.
Thanks again !
