### ISSUE TITLE
zsh-bench: utility 'script' from util-linux is required

### ISSUE THREAD

**Issue by johntdyer** [romkatv/zsh-bench#3]
I've installed util-linux on my mac and added it to the path.  Everytime I try to run it returns the following:

```
➜  rose git:(main) ~/zsh-bench/zsh-bench

zsh-bench: utility 'script' from util-linux is required
➜  rose git:(main)```

**Comment by johntdyer** [comment]
script -V doesnt work 

```
➜  plugins git:(master) script -V
script: illegal option -- V
usage: script [-adkpqr] [-t time] [file [command ...]]
➜  plugins git:(master)
```

**Comment by romkatv** [comment]
So it's not from util-linux. It's the BSD one.

**Comment by Moulick** [comment]
Hey, I hit into this today. So did `brew install util-linux`. but this formula is missing `script`. It has a plethora of other binaries but script it missing. What would be the best way to get `script` on macos ?

**Comment by romkatv** [comment]
> What would be the best way to get `script` on macos ?

I don't know.

**Comment by romkatv** [comment]
FYI: `zsh-bench` now works with BSD `script`, so it should just work on macOS.

**Comment by Moulick** [comment]
@romkatv woah, thanks a bunch, I'll try it out :)
