### ISSUE TITLE
Adding zpm to the bnecnhmark

### ISSUE THREAD

**Issue by arnavgr** [romkatv/zsh-bench#30]
Please take a look at [zpm](https://github.com/zpm-zsh/zpm), it claims to be the fastest zsh plugin manager, i juts want to see whether that is true or not and how fast it actually is

**Comment by romkatv** [comment]
I welcome the author of zpm to provide a proof of their statement.

On a more serious note, the speed of zsh plugin managers has virtually no effect on perceived interactive zsh latency.
