### ISSUE TITLE
zsh-bench hangs even on an empty .zshrc

### ISSUE THREAD

**Issue by dpi0** [romkatv/zsh-bench#31]
yesterday it ran perfectly fine on a fresh arch installation, but today it just hangs up indefinitely.

`zsh version: 5.9`
`zsh-bench version: latest`

i tried:
- running on my custom .zshrc with p10k and other plugins
- removing my .zshrc and all other configs related
- replacing it with an empty .zshrc file
- rebooting multiple times 
- running this fix: `~/zsh-bench/dbg/replay --scratch-dir /tmp/zsh-bench`, gives:
```
"builtin" "." "./s"
bash: line 1: builtin: emulate: not a shell builtin
```
- this [fix](https://github.com/romkatv/zsh-bench/issues/6#issuecomment-1031205503)

and nothing worked. it still hangs up indefinitely.

**Comment by romkatv** [comment]
What does `printenv SHELL` say?

**Comment by dpi0** [comment]
@romkatv i reinstalled arch on my system and now `~/zsh-bench/zsh-bench` works, on the previous install it never did work.

iirc at that time, `printenv SHELL` said `/bin/zsh`

now i'm not sure whether to close this issue, or wait till i encounter this issue again.
