### ISSUE TITLE
zsh is printing hostname or the last part of the current directory

### ISSUE THREAD

**Issue by Moulick** [romkatv/zsh-bench#7]
Hi, zsh-bench just exits after printing `zsh-bench: zsh is printing hostname or the last part of the current directory`. How can I figure out what's causing this ?

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
zsh -lic 'builtin exit' 2>&1 | command cat -v
```

**Comment by Moulick** [comment]
```bash
$ zsh -lic 'builtin exit' 2>&1 | command cat -v
^[]1337;RemoteHost=moulick.aggarwal@Moulick-Mac.local^G^[]1337;CurrentDir=/Users/moulick.aggarwal^G^[]1337;ShellIntegrationVersion=12;shell=zsh^G%
```

Exactly the above from my home directory

**Comment by romkatv** [comment]
Thanks. The check is overly aggressive. Should be fixed now. Please update zsh-bench and try again.

**Comment by Moulick** [comment]
well, my results are in, they are atrocious, this is currently running with your p10k and instant prompt enabled. That's the only thing keeping my shell even working

```bash
❯ ~/zsh-bench/zsh-bench
creates_tty=0
has_compsys=1
has_syntax_highlighting=1
has_autosuggestions=1
has_git_prompt=1
first_prompt_lag_ms=25.234
first_command_lag_ms=1353.146
command_lag_ms=37.501
input_lag_ms=8.305
exit_time_ms=925.338
```

**Comment by romkatv** [comment]
> the issue is fixed, thanks :)

Thanks for reporting the bug and verifying the fix!
